#!/bin/bash
Color_Off='\033[0m'       # Text Reset

# Regular
Orange='\033[0;93m'
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bright
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White
printf "${Cyan}"
echo ██████╗░░█████╗░░█████╗░██╗░░██╗███████╗████████╗███████╗██╗░██████╗██╗░░██╗░░
echo ██╔══██╗██╔══██╗██╔══██╗██║░██╔╝██╔════╝╚══██╔══╝██╔════╝██║██╔════╝██║░░██║░░
echo ██████╔╝███████║██║░░╚═╝█████═╝░█████╗░░░░░██║░░░█████╗░░██║╚█████╗░███████║░░
echo ██╔═══╝░██╔══██║██║░░██╗██╔═██╗░██╔══╝░░░░░██║░░░██╔══╝░░██║░╚═══██╗██╔══██║░░
echo ██║░░░░░██║░░██║╚█████╔╝██║░╚██╗███████╗░░░██║░░░██║░░░░░██║██████╔╝██║░░██║░░
printf "${Color_Off}"
printf "Packet capturer made by" 
printf "${Orange} @Chucny\n"
printf "${Color_Off}This is a simple tool made for capturing packets. Please don't use this tool for hacking people with it.\n"
echo How many packets would you like to capture?
read packets
echo Wich source?
read source
echo Wich port?
read portnumber
sudo tcpdump -i $source -c$packets -nn -A port $portnumber
